services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5434:5432" # Optional, expose PostgreSQL to external systems if needed
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - your_shared_network # In order for the backend to communicate with the frontend, we need a network. Make sure this points to the same in the frontend's docker-compose.yml file (this network should be created using the command `docker network create your_shared_network`)

volumes:
  postgres_data:

networks:
  your_shared_network: # Do not forget to rename it here as well
    external: true
