version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5434:5432" # Optional, expose PostgreSQL to external systems if needed
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - your_shared_network # Make sure this network is the same as the one for the frontend

volumes:
  postgres_data:

networks:
  your_shared_network: # Do not forget to rename it here as well
    external: true
